In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("stockData.csv")
df

,Date,series,OPEN,HIGH,LOW,PREV. CLOSE,ltp,close,vwap,52W H,52W L,VOLUME,VALUE,No of trades
0,26-Apr-2021,EQ,940.00,954.50,923.05,955.65,930.00,928.80,931.70,"1,067.00",467.25,"1,96,19,972","18,27,99,65,685.85","3,11,431"
1,23-Apr-2021,EQ,964.00,974.85,950.20,961.90,956.50,955.65,962.69,"1,067.00",447.85,"60,23,490","5,79,87,44,595.95","1,25,365"
2,22-Apr-2021,EQ,966.00,971.90,955.30,961.30,960.80,961.90,963.72,"1,067.00",447.85,"49,70,596","4,79,02,76,448.65","1,24,163"
3,20-Apr-2021,EQ,"1,006.00","1,006.00",957.00,994.60,960.90,961.30,972.08,"1,067.00",447.85,"97,42,418","9,47,03,62,573.40","2,11,611"
4,19-Apr-2021,EQ,996.00,"1,028.45",987.85,"1,012.75",990.00,994.60,"1,008.95","1,067.00",447.85,"62,39,343","6,29,52,07,034.30","1,41,513"
5,16-Apr-2021,EQ,"1,000.00","1,016.80",994.50,991.90,"1,016.00","1,012.75","1,009.97","1,067.00",447.85,"46,77,808","4,72,44,44,556.45","80,815"
6,15-Apr-2021,EQ,968.00,994.70,958.75,983.40,994.00,991.90,976.91,"1,067.00",447.85,"74,30,279","7,25,87,37,461.05","2,10,308"
7,13-Apr-2021,EQ,"1,012.50","1,020.80",972.20,"1,009.40",988.30,983.40,991.02,"1,067.00",447.85,"77,73,994","7,70,42,18,737.95","1,91,456"
8,12-Apr-2021,EQ,"1,042.95","1,042.95","1,001.20","1,045.40","1,012.95","1,009.40","1,015.97","1,067.00",447.85,"59,76,427","6,07,18,95,752.75","1,41,109"
9,09-Apr-2021,EQ,"1,042.10","1,054.80","1,034.15","1,037.50","1,043.05","1,045.40","1,044.97","1,067.00",425.00,"37,08,082","3,87,48,42,000.00","82,356"
10,08-Apr-2021,EQ,"1,044.00","1,054.40","1,031.65","1,037.20","1,037.15","1,037.50","1,041.24","1,067.00",425.00,"48,52,068","5,05,21,73,109.20","1,20,480"
11,07-Apr-2021,EQ,"1,031.00","1,045.00","1,024.70","1,028.40","1,037.00","1,037.20","1,034.68","1,067.00",425.00,"35,51,106","3,67,42,64,937.80","1,05,511"
12,06-Apr-2021,EQ,"1,039.00","1,040.60","1,020.25","1,033.50","1,029.00","1,028.40","1,028.99","1,067.00",425.00,"42,60,257","4,38,37,77,397.65","1,26,271"
13,05-Apr-2021,EQ,"1,007.00","1,040.00","1,002.60","1,002.60","1,034.55","1,033.50","1,022.68","1,067.00",425.00,"94,52,833","9,66,72,01,514.45","2,35,092"
14,01-Apr-2021,EQ,992.00,"1,013.50",990.60,982.65,"1,000.60","1,002.60","1,004.36","1,067.00",399.30,"52,69,079","5,29,20,29,105.00","97,439"
15,31-Mar-2021,EQ,"1,000.00","1,000.00",978.65,995.80,984.10,982.65,988.70,"1,067.00",399.30,"44,45,140","4,39,49,22,519.45","91,412"
16,30-Mar-2021,EQ,965.00,"1,000.80",964.45,958.55,995.10,995.80,986.21,"1,067.00",399.30,"54,75,051","5,39,95,51,432.65","1,21,367"
17,26-Mar-2021,EQ,965.00,975.00,953.80,957.05,960.00,958.55,962.80,"1,067.00",399.30,"42,71,178","4,11,22,72,425.60","96,782"